# Generated by Django 4.0.2 on 2024-04-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos_api', '0002_carrera_alumno_dni_alter_alumno_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
    ]
