# Generated by Django 4.0.2 on 2024-04-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos_api', '0004_actualizacioncarrera_creacioncarrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.IntegerField()),
                ('Modificacion', models.TextField(default='')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreacionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=200)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
