# Generated by Django 4.0.2 on 2024-04-19 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos_api', '0005_actualizacionalumno_creacionalumno_eliminacionalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='DNI',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
